services:
  _defaults:
    public: false
    autoconfigure: true
    autowire: true
    bind:
      $configDir: "%kernel.project_dir%/config"
  Codifyo\MakerBundle\:
    resource: '../../*'
    exclude: '../../{Tests,Resources}'
